apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-hello-api
  namespace: apps
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "ab555900-5ae7-4376-bf4f-5411719ed694"
    tenantId: "004b1179-227e-44f2-b759-e9f05b015b7b"
    keyvaultName: "kv-core-uat-justino"
    objects: |
      array:
        - |
          objectName: "hello-api-message"
          objectType: "secret"
          objectAlias: "hello-api-message"
  secretObjects:
    - secretName: hello-api-from-akv
      type: Opaque
      data:
        - key: message
          objectName: hello-api-message