name: Build and Deploy hello-api image (dev)

on:
  push:
    branches:
      - main
    paths:
      - "apps/hello-api/**"
      - ".github/workflows/build-hello-api-dev.yml"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-dev:
    #runs-on: ubuntu-latest
    runs-on: self-hosted 

    env:
      ACR_NAME: acrdevjustino
      IMAGE_NAME: hello-api
      IMAGE_TAG: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get ACR login server
        id: acr
        shell: pwsh
        run: |
          $loginServer = az acr show --name $env:ACR_NAME --query "loginServer" -o tsv
          Write-Host "ACR login server: $loginServer"
          "ACR_LOGIN_SERVER=$loginServer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Login to ACR
        shell: pwsh
        run: |
          az acr login --name $env:ACR_NAME

      - name: Build and push image
        shell: pwsh
        run: |
          Write-Host "ACR_LOGIN_SERVER: $env:ACR_LOGIN_SERVER"
          Write-Host "IMAGE_NAME: $env:IMAGE_NAME"
          Write-Host "IMAGE_TAG: $env:IMAGE_TAG"

          $image = "{0}/{1}:{2}" -f $env:ACR_LOGIN_SERVER, $env:IMAGE_NAME, $env:IMAGE_TAG
          Write-Host "Building image $image"

          docker build -t $image ./apps/hello-api
          docker push $image

  deploy-dev:
    needs: build-and-push-dev
    runs-on: ubuntu-latest

    steps:
      - name: Azure login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.32.0"

      - name: Get AKS credentials (DEV)
        shell: pwsh
        run: |
          az aks get-credentials `
            --resource-group rg-core-dev `
            --name aks-core-dev `
            --overwrite-existing

      - name: Restart hello-api deployment in DEV
        shell: pwsh
        run: |
          kubectl rollout restart deployment/hello-api -n apps
          kubectl rollout status deployment/hello-api -n apps --timeout=180s